---
- hosts: devpc

  vars:
    state: present

  tasks:
    - name: Install bruno via snap
      become: true
      community.general.snap:
        name: bruno
        state: present
        classic: false
      when: state == 'present'

    - name: Uninstall bruno via snap
      become: true
      community.general.snap:
        name: bruno
        state: absent
      when: state == 'absent'
