---
- hosts: devpc

  vars:
    state: present

  tasks:
    - name: Install steam via snap
      become: true
      community.general.snap:
        name: steam
        state: present
        classic: true
      when: state == 'present'

    - name: Uninstall steam via snap
      become: true
      community.general.snap:
        name: steam
        state: absent
      when: state == 'absent'
